# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'responsive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 720)
        MainWindow.setStyleSheet("color: white;")
        self.MainLayout = QtWidgets.QWidget(MainWindow)
        self.MainLayout.setMinimumSize(QtCore.QSize(1080, 720))
        self.MainLayout.setMaximumSize(QtCore.QSize(1920, 1080))
        self.MainLayout.setObjectName("MainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainLayout)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftBar = QtWidgets.QWidget(self.MainLayout)
        self.LeftBar.setMinimumSize(QtCore.QSize(180, 0))
        self.LeftBar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LeftBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LeftBar.setStyleSheet("QWidget{\n"
"    background-color: rgb(39, 38, 39);\n"
"}\n"
"QPushButton{\n"
"\n"
"    color:white;\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    border-bottom: 4px solid;\n"
"    border-right: 4px solid \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: \"#3d3d3d\";\n"
"     color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 2px solid;\n"
"    border-right: 2px solid\n"
"}\n"
"")
        self.LeftBar.setObjectName("LeftBar")
        self.gridLayout = QtWidgets.QGridLayout(self.LeftBar)
        self.gridLayout.setContentsMargins(5, 20, 5, 120)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.leftMenuButtons = QtWidgets.QVBoxLayout()
        self.leftMenuButtons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftMenuButtons.setContentsMargins(-1, -1, 0, -1)
        self.leftMenuButtons.setSpacing(7)
        self.leftMenuButtons.setObjectName("leftMenuButtons")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.leftMenuButtons.addItem(spacerItem)
        self.homeButton = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.homeButton.setFont(font)
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setMouseTracking(True)
        self.homeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.homeButton.setStyleSheet("color:white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("user/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.homeButton.setIcon(icon)
        self.homeButton.setFlat(True)
        self.homeButton.setObjectName("homeButton")
        self.leftMenuButtons.addWidget(self.homeButton)
        self.myTaskButton = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myTaskButton.sizePolicy().hasHeightForWidth())
        self.myTaskButton.setSizePolicy(sizePolicy)
        self.myTaskButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.myTaskButton.setFont(font)
        self.myTaskButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.myTaskButton.setStyleSheet("color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("user/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.myTaskButton.setIcon(icon1)
        self.myTaskButton.setFlat(True)
        self.myTaskButton.setObjectName("myTaskButton")
        self.leftMenuButtons.addWidget(self.myTaskButton)
        self.guideButton = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guideButton.sizePolicy().hasHeightForWidth())
        self.guideButton.setSizePolicy(sizePolicy)
        self.guideButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.guideButton.setFont(font)
        self.guideButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.guideButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.guideButton.setStyleSheet("color: white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("user/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.guideButton.setIcon(icon2)
        self.guideButton.setDefault(False)
        self.guideButton.setFlat(True)
        self.guideButton.setObjectName("guideButton")
        self.leftMenuButtons.addWidget(self.guideButton)
        self.logOutButton = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logOutButton.sizePolicy().hasHeightForWidth())
        self.logOutButton.setSizePolicy(sizePolicy)
        self.logOutButton.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logOutButton.setStyleSheet("color: white;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("user/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.logOutButton.setIcon(icon3)
        self.logOutButton.setFlat(True)
        self.logOutButton.setObjectName("logOutButton")
        self.leftMenuButtons.addWidget(self.logOutButton)
        self.gridLayout.addLayout(self.leftMenuButtons, 5, 0, 1, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hideLeftMenu = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideLeftMenu.sizePolicy().hasHeightForWidth())
        self.hideLeftMenu.setSizePolicy(sizePolicy)
        self.hideLeftMenu.setMinimumSize(QtCore.QSize(45, 45))
        self.hideLeftMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hideLeftMenu.setStyleSheet("color: white;")
        self.hideLeftMenu.setObjectName("hideLeftMenu")
        self.gridLayout_4.addWidget(self.hideLeftMenu, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.LeftBar)
        self.widget_7.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_7.setMaximumSize(QtCore.QSize(150, 150))
        self.widget_7.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-image: url(user/account.png);\n"
"border-radius: 75%;")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_5.addWidget(self.widget_7, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.LeftBar)
        self.Middle = QtWidgets.QWidget(self.MainLayout)
        self.Middle.setEnabled(True)
        self.Middle.setMinimumSize(QtCore.QSize(700, 0))
        self.Middle.setMaximumSize(QtCore.QSize(1240, 16777215))
        self.Middle.setStyleSheet("")
        self.Middle.setObjectName("Middle")
        self.middleLayout = QtWidgets.QGridLayout(self.Middle)
        self.middleLayout.setObjectName("middleLayout")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.middleLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.middleLayout.addItem(spacerItem4, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.middleLayout.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.middleLayout.addItem(spacerItem6, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 0, 1, 1)
        self.addTasks = QtWidgets.QWidget(self.Middle)
        self.addTasks.setMinimumSize(QtCore.QSize(300, 50))
        self.addTasks.setMaximumSize(QtCore.QSize(600, 80))
        self.addTasks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addTasks.setStyleSheet("background-color:rgb(253, 89, 89);\n"
"border-radius: 25%;")
        self.addTasks.setObjectName("addTasks")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.addTasks)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.taskListLabel = QtWidgets.QLabel(self.addTasks)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.taskListLabel.setFont(font)
        self.taskListLabel.setStyleSheet("color: white;")
        self.taskListLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.taskListLabel.setObjectName("taskListLabel")
        self.horizontalLayout_2.addWidget(self.taskListLabel)
        self.taskListIcon = QtWidgets.QPushButton(self.addTasks)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskListIcon.sizePolicy().hasHeightForWidth())
        self.taskListIcon.setSizePolicy(sizePolicy)
        self.taskListIcon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.taskListIcon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("user/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.taskListIcon.setIcon(icon4)
        self.taskListIcon.setIconSize(QtCore.QSize(50, 50))
        self.taskListIcon.setObjectName("taskListIcon")
        self.horizontalLayout_2.addWidget(self.taskListIcon)
        self.gridLayout_2.addWidget(self.addTasks, 0, 2, 1, 1)
        self.middleLayout.addLayout(self.gridLayout_2, 5, 1, 1, 2)
        self.matrix = QtWidgets.QGridLayout()
        self.matrix.setSpacing(0)
        self.matrix.setObjectName("matrix")
        self.upLeft = QtWidgets.QWidget(self.Middle)
        self.upLeft.setStyleSheet("QWidget{\n"
"background-color: rgb(252, 158, 158);\n"
"}")
        self.upLeft.setObjectName("upLeft")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.upLeft)
        self.gridLayout_9.setContentsMargins(18, 10, 5, 5)
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.do_label = QtWidgets.QLabel(self.upLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.do_label.sizePolicy().hasHeightForWidth())
        self.do_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.do_label.setFont(font)
        self.do_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.do_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.do_label.setObjectName("do_label")
        self.gridLayout_9.addWidget(self.do_label, 0, 0, 1, 1)
        self.addDoTask = QtWidgets.QPushButton(self.upLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDoTask.sizePolicy().hasHeightForWidth())
        self.addDoTask.setSizePolicy(sizePolicy)
        self.addDoTask.setMinimumSize(QtCore.QSize(10, 10))
        self.addDoTask.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addDoTask.setFont(font)
        self.addDoTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addDoTask.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    border-radius: 10px;\n"
"    background-color: \"#cccccc\";\n"
"    border-bottom: 2px solid \"#3d3d3d\";\n"
"    border-right: 2px solid \"#3d3d3d\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: \"#3d3d3d\";\n"
"     color: white;\n"
"    border-bottom: 2px solid \"#cccccc\";\n"
"    border-right: 2px solid \"#cccccc\";\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 1px solid \"#cccccc\";\n"
"    border-right: 1px solid \"#cccccc\";\n"
"}")
        self.addDoTask.setObjectName("addDoTask")
        self.gridLayout_9.addWidget(self.addDoTask, 2, 1, 1, 1)
        self.do_matrix = QtWidgets.QGridLayout()
        self.do_matrix.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.do_matrix.setSpacing(8)
        self.do_matrix.setObjectName("do_matrix")
        self.do_task2 = QtWidgets.QWidget(self.upLeft)
        self.do_task2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.do_task2.setObjectName("do_task2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.do_task2)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.do_task2_button = QtWidgets.QPushButton(self.do_task2)
        self.do_task2_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.do_task2_button.setText("")
        self.do_task2_button.setProperty("ID", -1)
        self.do_task2_button.setObjectName("do_task2_button")
        self.gridLayout_22.addWidget(self.do_task2_button, 0, 0, 1, 1)
        self.do_matrix.addWidget(self.do_task2, 0, 1, 1, 1)
        self.do_task3 = QtWidgets.QWidget(self.upLeft)
        self.do_task3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.do_task3.setObjectName("do_task3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.do_task3)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.do_task3_button = QtWidgets.QPushButton(self.do_task3)
        self.do_task3_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.do_task3_button.setText("")
        self.do_task3_button.setProperty("ID", -1)
        self.do_task3_button.setObjectName("do_task3_button")
        self.gridLayout_13.addWidget(self.do_task3_button, 0, 0, 1, 1)
        self.do_matrix.addWidget(self.do_task3, 0, 2, 1, 1)
        self.do_task6 = QtWidgets.QWidget(self.upLeft)
        self.do_task6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.do_task6.setObjectName("do_task6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.do_task6)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.do_task6_button = QtWidgets.QPushButton(self.do_task6)
        self.do_task6_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.do_task6_button.setText("")
        self.do_task6_button.setProperty("ID", -1)
        self.do_task6_button.setObjectName("do_task6_button")
        self.gridLayout_14.addWidget(self.do_task6_button, 0, 0, 1, 1)
        self.do_matrix.addWidget(self.do_task6, 1, 2, 1, 1)
        self.do_task5 = QtWidgets.QWidget(self.upLeft)
        self.do_task5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.do_task5.setObjectName("do_task5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.do_task5)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.do_task5_button = QtWidgets.QPushButton(self.do_task5)
        self.do_task5_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.do_task5_button.setText("")
        self.do_task5_button.setProperty("ID", -1)
        self.do_task5_button.setObjectName("do_task5_button")
        self.gridLayout_15.addWidget(self.do_task5_button, 0, 0, 1, 1)
        self.do_matrix.addWidget(self.do_task5, 1, 1, 1, 1)
        self.do_task4 = QtWidgets.QWidget(self.upLeft)
        self.do_task4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.do_task4.setObjectName("do_task4")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.do_task4)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.do_task4_button = QtWidgets.QPushButton(self.do_task4)
        self.do_task4_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.do_task4_button.setText("")
        self.do_task4_button.setProperty("ID", -1)
        self.do_task4_button.setObjectName("do_task4_button")
        self.gridLayout_21.addWidget(self.do_task4_button, 0, 0, 1, 1)
        self.do_matrix.addWidget(self.do_task4, 1, 0, 1, 1)
        self.do_task1 = QtWidgets.QWidget(self.upLeft)
        self.do_task1.setEnabled(False)
        self.do_task1.setStyleSheet("border: 1px dashed;\n"
"border-color: black;\n"
"border-radius: 10px;\n"
"")
        self.do_task1.setObjectName("do_task1")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.do_task1)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.do_task1_button = QtWidgets.QPushButton(self.do_task1)
        self.do_task1_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.do_task1_button.setText("")
        self.do_task1_button.setProperty("ID", -1)
        self.do_task1_button.setObjectName("do_task1_button")
        self.gridLayout_16.addWidget(self.do_task1_button, 0, 0, 1, 1)
        self.do_matrix.addWidget(self.do_task1, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.do_matrix, 1, 0, 1, 1)
        self.colorsDoTasks = QtWidgets.QPushButton(self.upLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorsDoTasks.sizePolicy().hasHeightForWidth())
        self.colorsDoTasks.setSizePolicy(sizePolicy)
        self.colorsDoTasks.setMinimumSize(QtCore.QSize(10, 10))
        self.colorsDoTasks.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorsDoTasks.setFont(font)
        self.colorsDoTasks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.colorsDoTasks.setStyleSheet("color: black;")
        self.colorsDoTasks.setObjectName("colorsDoTasks")
        self.gridLayout_9.addWidget(self.colorsDoTasks, 0, 1, 1, 1)
        self.matrix.addWidget(self.upLeft, 0, 0, 1, 1)
        self.upRight = QtWidgets.QWidget(self.Middle)
        self.upRight.setStyleSheet("QWidget{\n"
"background-color: rgb(166, 166, 255);\n"
"}")
        self.upRight.setObjectName("upRight")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.upRight)
        self.gridLayout_12.setContentsMargins(18, 10, 3, 5)
        self.gridLayout_12.setHorizontalSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.colorsScheduleTasks = QtWidgets.QPushButton(self.upRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorsScheduleTasks.sizePolicy().hasHeightForWidth())
        self.colorsScheduleTasks.setSizePolicy(sizePolicy)
        self.colorsScheduleTasks.setMinimumSize(QtCore.QSize(10, 10))
        self.colorsScheduleTasks.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorsScheduleTasks.setFont(font)
        self.colorsScheduleTasks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.colorsScheduleTasks.setStyleSheet("color: black;")
        self.colorsScheduleTasks.setObjectName("colorsScheduleTasks")
        self.gridLayout_12.addWidget(self.colorsScheduleTasks, 0, 1, 1, 1)
        self.schedule_label = QtWidgets.QLabel(self.upRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_label.sizePolicy().hasHeightForWidth())
        self.schedule_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.schedule_label.setFont(font)
        self.schedule_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.schedule_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.schedule_label.setObjectName("schedule_label")
        self.gridLayout_12.addWidget(self.schedule_label, 0, 0, 1, 1)
        self.addScheduleTask = QtWidgets.QPushButton(self.upRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addScheduleTask.sizePolicy().hasHeightForWidth())
        self.addScheduleTask.setSizePolicy(sizePolicy)
        self.addScheduleTask.setMinimumSize(QtCore.QSize(10, 10))
        self.addScheduleTask.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addScheduleTask.setFont(font)
        self.addScheduleTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addScheduleTask.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    border-radius: 10px;\n"
"    background-color: \"#cccccc\";\n"
"    border-bottom: 2px solid \"#3d3d3d\";\n"
"    border-right: 2px solid \"#3d3d3d\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: \"#3d3d3d\";\n"
"     color: white;\n"
"    border-bottom: 2px solid \"#cccccc\";\n"
"    border-right: 2px solid \"#cccccc\";\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 1px solid \"#cccccc\";\n"
"    border-right: 1px solid \"#cccccc\";\n"
"}")
        self.addScheduleTask.setObjectName("addScheduleTask")
        self.gridLayout_12.addWidget(self.addScheduleTask, 2, 1, 1, 1)
        self.schedule_matrix = QtWidgets.QGridLayout()
        self.schedule_matrix.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.schedule_matrix.setSpacing(8)
        self.schedule_matrix.setObjectName("schedule_matrix")
        self.schedule_task6 = QtWidgets.QWidget(self.upRight)
        self.schedule_task6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.schedule_task6.setObjectName("schedule_task6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.schedule_task6)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.schedule_task6_button = QtWidgets.QPushButton(self.schedule_task6)
        self.schedule_task6_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.schedule_task6_button.setText("")
        self.schedule_task6_button.setProperty("ID", -1)
        self.schedule_task6_button.setObjectName("schedule_task6_button")
        self.gridLayout_19.addWidget(self.schedule_task6_button, 0, 0, 1, 1)
        self.schedule_matrix.addWidget(self.schedule_task6, 1, 2, 1, 1)
        self.schedule_task3 = QtWidgets.QWidget(self.upRight)
        self.schedule_task3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.schedule_task3.setObjectName("schedule_task3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.schedule_task3)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.schedule_task3_button = QtWidgets.QPushButton(self.schedule_task3)
        self.schedule_task3_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.schedule_task3_button.setText("")
        self.schedule_task3_button.setProperty("ID", -1)
        self.schedule_task3_button.setObjectName("schedule_task3_button")
        self.gridLayout_18.addWidget(self.schedule_task3_button, 0, 0, 1, 1)
        self.schedule_matrix.addWidget(self.schedule_task3, 0, 2, 1, 1)
        self.schedule_task5 = QtWidgets.QWidget(self.upRight)
        self.schedule_task5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.schedule_task5.setObjectName("schedule_task5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.schedule_task5)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.schedule_task5_button = QtWidgets.QPushButton(self.schedule_task5)
        self.schedule_task5_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.schedule_task5_button.setText("")
        self.schedule_task5_button.setProperty("ID", -1)
        self.schedule_task5_button.setObjectName("schedule_task5_button")
        self.gridLayout_20.addWidget(self.schedule_task5_button, 0, 0, 1, 1)
        self.schedule_matrix.addWidget(self.schedule_task5, 1, 1, 1, 1)
        self.schedule_task1 = QtWidgets.QWidget(self.upRight)
        self.schedule_task1.setStyleSheet("border: 1px dashed;\n"
"border-color: red;\n"
"border-radius: 10px;")
        self.schedule_task1.setObjectName("schedule_task1")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.schedule_task1)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.schedule_task1_button = QtWidgets.QPushButton(self.schedule_task1)
        self.schedule_task1_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.schedule_task1_button.setText("")
        self.schedule_task1_button.setProperty("ID", -1)
        self.schedule_task1_button.setObjectName("schedule_task1_button")
        self.gridLayout_25.addWidget(self.schedule_task1_button, 0, 0, 1, 1)
        self.schedule_matrix.addWidget(self.schedule_task1, 0, 0, 1, 1)
        self.schedule_task4 = QtWidgets.QWidget(self.upRight)
        self.schedule_task4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.schedule_task4.setObjectName("schedule_task4")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.schedule_task4)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.schedule_task4_button = QtWidgets.QPushButton(self.schedule_task4)
        self.schedule_task4_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.schedule_task4_button.setText("")
        self.schedule_task4_button.setProperty("ID", -1)
        self.schedule_task4_button.setObjectName("schedule_task4_button")
        self.gridLayout_27.addWidget(self.schedule_task4_button, 0, 0, 1, 1)
        self.schedule_matrix.addWidget(self.schedule_task4, 1, 0, 1, 1)
        self.schedule_task2 = QtWidgets.QWidget(self.upRight)
        self.schedule_task2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.schedule_task2.setObjectName("schedule_task2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.schedule_task2)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.schedule_task2_button = QtWidgets.QPushButton(self.schedule_task2)
        self.schedule_task2_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.schedule_task2_button.setText("")
        self.schedule_task2_button.setProperty("ID", -1)
        self.schedule_task2_button.setObjectName("schedule_task2_button")
        self.gridLayout_28.addWidget(self.schedule_task2_button, 0, 0, 1, 1)
        self.schedule_matrix.addWidget(self.schedule_task2, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.schedule_matrix, 1, 0, 1, 1)
        self.matrix.addWidget(self.upRight, 0, 1, 1, 1)
        self.downRight = QtWidgets.QWidget(self.Middle)
        self.downRight.setStyleSheet("QWidget{\n"
"background-color: rgb(164, 255, 164);\n"
"}")
        self.downRight.setObjectName("downRight")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.downRight)
        self.gridLayout_31.setContentsMargins(18, 10, 5, 5)
        self.gridLayout_31.setHorizontalSpacing(0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.colorsDeleteTasks = QtWidgets.QPushButton(self.downRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorsDeleteTasks.sizePolicy().hasHeightForWidth())
        self.colorsDeleteTasks.setSizePolicy(sizePolicy)
        self.colorsDeleteTasks.setMinimumSize(QtCore.QSize(10, 10))
        self.colorsDeleteTasks.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorsDeleteTasks.setFont(font)
        self.colorsDeleteTasks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.colorsDeleteTasks.setStyleSheet("color: black;")
        self.colorsDeleteTasks.setObjectName("colorsDeleteTasks")
        self.gridLayout_31.addWidget(self.colorsDeleteTasks, 0, 1, 1, 1)
        self.delete_label = QtWidgets.QLabel(self.downRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_label.sizePolicy().hasHeightForWidth())
        self.delete_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.delete_label.setFont(font)
        self.delete_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.delete_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.delete_label.setObjectName("delete_label")
        self.gridLayout_31.addWidget(self.delete_label, 0, 0, 1, 1)
        self.addDeleteTask = QtWidgets.QPushButton(self.downRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDeleteTask.sizePolicy().hasHeightForWidth())
        self.addDeleteTask.setSizePolicy(sizePolicy)
        self.addDeleteTask.setMinimumSize(QtCore.QSize(10, 10))
        self.addDeleteTask.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addDeleteTask.setFont(font)
        self.addDeleteTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addDeleteTask.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    border-radius: 10px;\n"
"    background-color: \"#cccccc\";\n"
"    border-bottom: 2px solid \"#3d3d3d\";\n"
"    border-right: 2px solid \"#3d3d3d\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: \"#3d3d3d\";\n"
"     color: white;\n"
"    border-bottom: 2px solid \"#cccccc\";\n"
"    border-right: 2px solid \"#cccccc\";\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 1px solid \"#cccccc\";\n"
"    border-right: 1px solid \"#cccccc\";\n"
"}")
        self.addDeleteTask.setObjectName("addDeleteTask")
        self.gridLayout_31.addWidget(self.addDeleteTask, 2, 1, 1, 1)
        self.delete_matrix = QtWidgets.QGridLayout()
        self.delete_matrix.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.delete_matrix.setSpacing(8)
        self.delete_matrix.setObjectName("delete_matrix")
        self.delete_task3 = QtWidgets.QWidget(self.downRight)
        self.delete_task3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delete_task3.setObjectName("delete_task3")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.delete_task3)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.delete_task3_button = QtWidgets.QPushButton(self.delete_task3)
        self.delete_task3_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delete_task3_button.setText("")
        self.delete_task3_button.setProperty("ID", -1)
        self.delete_task3_button.setObjectName("delete_task3_button")
        self.gridLayout_32.addWidget(self.delete_task3_button, 0, 0, 1, 1)
        self.delete_matrix.addWidget(self.delete_task3, 0, 2, 1, 1)
        self.delete_task6 = QtWidgets.QWidget(self.downRight)
        self.delete_task6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delete_task6.setObjectName("delete_task6")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.delete_task6)
        self.gridLayout_33.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.delete_task6_button = QtWidgets.QPushButton(self.delete_task6)
        self.delete_task6_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delete_task6_button.setText("")
        self.delete_task6_button.setProperty("ID", -1)
        self.delete_task6_button.setObjectName("delete_task6_button")
        self.gridLayout_33.addWidget(self.delete_task6_button, 0, 0, 1, 1)
        self.delete_matrix.addWidget(self.delete_task6, 1, 2, 1, 1)
        self.delete_task5 = QtWidgets.QWidget(self.downRight)
        self.delete_task5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delete_task5.setObjectName("delete_task5")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.delete_task5)
        self.gridLayout_34.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.delete_task5_button = QtWidgets.QPushButton(self.delete_task5)
        self.delete_task5_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delete_task5_button.setText("")
        self.delete_task5_button.setProperty("ID", -1)
        self.delete_task5_button.setObjectName("delete_task5_button")
        self.gridLayout_34.addWidget(self.delete_task5_button, 0, 0, 1, 1)
        self.delete_matrix.addWidget(self.delete_task5, 1, 1, 1, 1)
        self.delete_task1 = QtWidgets.QWidget(self.downRight)
        self.delete_task1.setStyleSheet("border: 1px dashed;\n"
"border-color: red;\n"
"border-radius: 10px;")
        self.delete_task1.setObjectName("delete_task1")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.delete_task1)
        self.gridLayout_35.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.delete_task1_button = QtWidgets.QPushButton(self.delete_task1)
        self.delete_task1_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delete_task1_button.setText("")
        self.delete_task1_button.setProperty("ID", -1)
        self.delete_task1_button.setObjectName("delete_task1_button")
        self.gridLayout_35.addWidget(self.delete_task1_button, 0, 0, 1, 1)
        self.delete_matrix.addWidget(self.delete_task1, 0, 0, 1, 1)
        self.delete_task4 = QtWidgets.QWidget(self.downRight)
        self.delete_task4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delete_task4.setObjectName("delete_task4")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.delete_task4)
        self.gridLayout_37.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.delete_task4_button = QtWidgets.QPushButton(self.delete_task4)
        self.delete_task4_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delete_task4_button.setText("")
        self.delete_task4_button.setProperty("ID", -1)
        self.delete_task4_button.setObjectName("delete_task4_button")
        self.gridLayout_37.addWidget(self.delete_task4_button, 0, 0, 1, 1)
        self.delete_matrix.addWidget(self.delete_task4, 1, 0, 1, 1)
        self.delete_task2 = QtWidgets.QWidget(self.downRight)
        self.delete_task2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delete_task2.setObjectName("delete_task2")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.delete_task2)
        self.gridLayout_38.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.delete_task2_button = QtWidgets.QPushButton(self.delete_task2)
        self.delete_task2_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delete_task2_button.setText("")
        self.delete_task2_button.setProperty("ID", -1)
        self.delete_task2_button.setObjectName("delete_task2_button")
        self.gridLayout_38.addWidget(self.delete_task2_button, 0, 0, 1, 1)
        self.delete_matrix.addWidget(self.delete_task2, 0, 1, 1, 1)
        self.gridLayout_31.addLayout(self.delete_matrix, 1, 0, 1, 1)
        self.matrix.addWidget(self.downRight, 1, 1, 1, 1)
        self.downLeft = QtWidgets.QWidget(self.Middle)
        self.downLeft.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 168);\n"
"}")
        self.downLeft.setObjectName("downLeft")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.downLeft)
        self.gridLayout_41.setContentsMargins(18, 10, 5, 5)
        self.gridLayout_41.setHorizontalSpacing(0)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.colorsDelegateTasks = QtWidgets.QPushButton(self.downLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorsDelegateTasks.sizePolicy().hasHeightForWidth())
        self.colorsDelegateTasks.setSizePolicy(sizePolicy)
        self.colorsDelegateTasks.setMinimumSize(QtCore.QSize(10, 10))
        self.colorsDelegateTasks.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorsDelegateTasks.setFont(font)
        self.colorsDelegateTasks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.colorsDelegateTasks.setStyleSheet("color: black;")
        self.colorsDelegateTasks.setObjectName("colorsDelegateTasks")
        self.gridLayout_41.addWidget(self.colorsDelegateTasks, 0, 1, 1, 1)
        self.delegate_label = QtWidgets.QLabel(self.downLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delegate_label.sizePolicy().hasHeightForWidth())
        self.delegate_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.delegate_label.setFont(font)
        self.delegate_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.delegate_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.delegate_label.setObjectName("delegate_label")
        self.gridLayout_41.addWidget(self.delegate_label, 0, 0, 1, 1)
        self.addDelegateTask = QtWidgets.QPushButton(self.downLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDelegateTask.sizePolicy().hasHeightForWidth())
        self.addDelegateTask.setSizePolicy(sizePolicy)
        self.addDelegateTask.setMinimumSize(QtCore.QSize(10, 10))
        self.addDelegateTask.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addDelegateTask.setFont(font)
        self.addDelegateTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addDelegateTask.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    border-radius: 10px;\n"
"    background-color: \"#cccccc\";\n"
"    border-bottom: 2px solid \"#3d3d3d\";\n"
"    border-right: 2px solid \"#3d3d3d\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: \"#3d3d3d\";\n"
"     color: white;\n"
"    border-bottom: 2px solid \"#cccccc\";\n"
"    border-right: 2px solid \"#cccccc\";\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 1px solid \"#cccccc\";\n"
"    border-right: 1px solid \"#cccccc\";\n"
"}")
        self.addDelegateTask.setObjectName("addDelegateTask")
        self.gridLayout_41.addWidget(self.addDelegateTask, 2, 1, 1, 1)
        self.delegate_matrix = QtWidgets.QGridLayout()
        self.delegate_matrix.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.delegate_matrix.setSpacing(8)
        self.delegate_matrix.setObjectName("delegate_matrix")
        self.delegate_task1 = QtWidgets.QWidget(self.downLeft)
        self.delegate_task1.setStyleSheet("border: 1px dashed;\n"
"border-color: red;\n"
"border-radius: 10px;")
        self.delegate_task1.setObjectName("delegate_task1")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.delegate_task1)
        self.gridLayout_45.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.delegate_task1_button = QtWidgets.QPushButton(self.delegate_task1)
        self.delegate_task1_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delegate_task1_button.setText("")
        self.delegate_task1_button.setProperty("ID", -1)
        self.delegate_task1_button.setObjectName("delegate_task1_button")
        self.gridLayout_45.addWidget(self.delegate_task1_button, 0, 0, 1, 1)
        self.delegate_matrix.addWidget(self.delegate_task1, 0, 0, 1, 1)
        self.delegate_task5 = QtWidgets.QWidget(self.downLeft)
        self.delegate_task5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delegate_task5.setObjectName("delegate_task5")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.delegate_task5)
        self.gridLayout_44.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.delegate_task5_button = QtWidgets.QPushButton(self.delegate_task5)
        self.delegate_task5_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delegate_task5_button.setText("")
        self.delegate_task5_button.setProperty("ID", -1)
        self.delegate_task5_button.setObjectName("delegate_task5_button")
        self.gridLayout_44.addWidget(self.delegate_task5_button, 0, 0, 1, 1)
        self.delegate_matrix.addWidget(self.delegate_task5, 1, 1, 1, 1)
        self.delegate_task3 = QtWidgets.QWidget(self.downLeft)
        self.delegate_task3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delegate_task3.setObjectName("delegate_task3")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.delegate_task3)
        self.gridLayout_42.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.delegate_task3_button = QtWidgets.QPushButton(self.delegate_task3)
        self.delegate_task3_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delegate_task3_button.setText("")
        self.delegate_task3_button.setProperty("ID", -1)
        self.delegate_task3_button.setObjectName("delegate_task3_button")
        self.gridLayout_42.addWidget(self.delegate_task3_button, 0, 0, 1, 1)
        self.delegate_matrix.addWidget(self.delegate_task3, 0, 2, 1, 1)
        self.delegate_task6 = QtWidgets.QWidget(self.downLeft)
        self.delegate_task6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delegate_task6.setObjectName("delegate_task6")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.delegate_task6)
        self.gridLayout_43.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.delegate_task6_button = QtWidgets.QPushButton(self.delegate_task6)
        self.delegate_task6_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delegate_task6_button.setText("")
        self.delegate_task6_button.setProperty("ID", -1)
        self.delegate_task6_button.setObjectName("delegate_task6_button")
        self.gridLayout_43.addWidget(self.delegate_task6_button, 0, 0, 1, 1)
        self.delegate_matrix.addWidget(self.delegate_task6, 1, 2, 1, 1)
        self.delegate_task4 = QtWidgets.QWidget(self.downLeft)
        self.delegate_task4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delegate_task4.setObjectName("delegate_task4")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.delegate_task4)
        self.gridLayout_47.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.delegate_task4_button = QtWidgets.QPushButton(self.delegate_task4)
        self.delegate_task4_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delegate_task4_button.setText("")
        self.delegate_task4_button.setProperty("ID", -1)
        self.delegate_task4_button.setObjectName("delegate_task4_button")
        self.gridLayout_47.addWidget(self.delegate_task4_button, 0, 0, 1, 1)
        self.delegate_matrix.addWidget(self.delegate_task4, 1, 0, 1, 1)
        self.delegate_task2 = QtWidgets.QWidget(self.downLeft)
        self.delegate_task2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius: 10px;")
        self.delegate_task2.setObjectName("delegate_task2")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.delegate_task2)
        self.gridLayout_48.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.delegate_task2_button = QtWidgets.QPushButton(self.delegate_task2)
        self.delegate_task2_button.setStyleSheet("QAbstractButton{\n"
"margin: 2px;\n"
"border: 0px;}")
        self.delegate_task2_button.setText("")
        self.delegate_task2_button.setProperty("ID", -1)
        self.delegate_task2_button.setObjectName("delegate_task2_button")
        self.gridLayout_48.addWidget(self.delegate_task2_button, 0, 0, 1, 1)
        self.delegate_matrix.addWidget(self.delegate_task2, 0, 1, 1, 1)
        self.gridLayout_41.addLayout(self.delegate_matrix, 1, 0, 1, 1)
        self.matrix.addWidget(self.downLeft, 1, 0, 1, 1)
        self.middleLayout.addLayout(self.matrix, 1, 1, 2, 2)
        self.horizontalLayout.addWidget(self.Middle)
        self.RightBar = QtWidgets.QWidget(self.MainLayout)
        self.RightBar.setMinimumSize(QtCore.QSize(200, 0))
        self.RightBar.setMaximumSize(QtCore.QSize(350, 16777215))
        self.RightBar.setStyleSheet("QWidget{\n"
"    background-color: rgb(39, 38, 39);\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    background-color: rgb(39, 38, 39);\n"
"    border-radius: 2px;\n"
"    border: 2px solid white;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"    background-color: white;\n"
"    background-image: url(user/check.png);\n"
"    border-radius: 2px;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 8px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border-radius: 8px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    border: 2px solid;\n"
"    border-radius: 8px;\n"
"    border-bottom: 4px solid;\n"
"    border-right: 4px solid \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: \"#3d3d3d\";\n"
"     color: black;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 2px solid;\n"
"    border-right: 2px solid\n"
"}\n"
"\n"
"")
        self.RightBar.setObjectName("RightBar")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.RightBar)
        self.gridLayout_6.setContentsMargins(10, 50, 10, 50)
        self.gridLayout_6.setHorizontalSpacing(5)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem9, 10, 1, 1, 1)
        self.deleteTaskButton = QtWidgets.QPushButton(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteTaskButton.sizePolicy().hasHeightForWidth())
        self.deleteTaskButton.setSizePolicy(sizePolicy)
        self.deleteTaskButton.setMaximumSize(QtCore.QSize(16777215, 70))
        self.deleteTaskButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteTaskButton.setFont(font)
        self.deleteTaskButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteTaskButton.setStyleSheet("color:black;\n"
"background-color: white;\n"
"")
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.gridLayout_6.addWidget(self.deleteTaskButton, 11, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_6.addItem(spacerItem10, 8, 1, 1, 1)
        self.taskManagerTitle = QtWidgets.QLabel(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.taskManagerTitle.sizePolicy().hasHeightForWidth())
        self.taskManagerTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.taskManagerTitle.setFont(font)
        self.taskManagerTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.taskManagerTitle.setObjectName("taskManagerTitle")
        self.gridLayout_6.addWidget(self.taskManagerTitle, 1, 0, 1, 3)
        self.rightMenuButtons = QtWidgets.QGridLayout()
        self.rightMenuButtons.setContentsMargins(-1, 15, -1, 15)
        self.rightMenuButtons.setHorizontalSpacing(0)
        self.rightMenuButtons.setVerticalSpacing(50)
        self.rightMenuButtons.setObjectName("rightMenuButtons")
        self.calendarIcon = QtWidgets.QLabel(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarIcon.sizePolicy().hasHeightForWidth())
        self.calendarIcon.setSizePolicy(sizePolicy)
        self.calendarIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.calendarIcon.setText("")
        self.calendarIcon.setPixmap(QtGui.QPixmap("user/calendar.png"))
        self.calendarIcon.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calendarIcon.setObjectName("calendarIcon")
        self.rightMenuButtons.addWidget(self.calendarIcon, 5, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.rightMenuButtons.addWidget(self.dateEdit, 5, 1, 1, 1)
        self.taskDescription = QtWidgets.QTextEdit(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskDescription.sizePolicy().hasHeightForWidth())
        self.taskDescription.setSizePolicy(sizePolicy)
        self.taskDescription.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taskDescription.setFont(font)
        self.taskDescription.setObjectName("taskDescription")
        self.rightMenuButtons.addWidget(self.taskDescription, 1, 0, 1, 2)
        self.taskNameInput = QtWidgets.QLineEdit(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskNameInput.sizePolicy().hasHeightForWidth())
        self.taskNameInput.setSizePolicy(sizePolicy)
        self.taskNameInput.setMinimumSize(QtCore.QSize(0, 0))
        self.taskNameInput.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taskNameInput.setFont(font)
        self.taskNameInput.setInputMask("")
        self.taskNameInput.setText("")
        self.taskNameInput.setDragEnabled(False)
        self.taskNameInput.setObjectName("taskNameInput")
        self.rightMenuButtons.addWidget(self.taskNameInput, 0, 0, 1, 2)
        self.completeLabel = QtWidgets.QLabel(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completeLabel.sizePolicy().hasHeightForWidth())
        self.completeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.completeLabel.setFont(font)
        self.completeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.completeLabel.setObjectName("completeLabel")
        self.rightMenuButtons.addWidget(self.completeLabel, 6, 1, 1, 1)
        self.completeCheckBox = QtWidgets.QCheckBox(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completeCheckBox.sizePolicy().hasHeightForWidth())
        self.completeCheckBox.setSizePolicy(sizePolicy)
        self.completeCheckBox.setMinimumSize(QtCore.QSize(50, 0))
        self.completeCheckBox.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.completeCheckBox.setFont(font)
        self.completeCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.completeCheckBox.setTabletTracking(False)
        self.completeCheckBox.setStyleSheet("")
        self.completeCheckBox.setText("")
        self.completeCheckBox.setIconSize(QtCore.QSize(30, 30))
        self.completeCheckBox.setTristate(False)
        self.completeCheckBox.setObjectName("completeCheckBox")
        self.rightMenuButtons.addWidget(self.completeCheckBox, 6, 0, 1, 1)
        self.taskPriorityLayout = QtWidgets.QVBoxLayout()
        self.taskPriorityLayout.setContentsMargins(-1, -1, -1, 0)
        self.taskPriorityLayout.setSpacing(10)
        self.taskPriorityLayout.setObjectName("taskPriorityLayout")
        self.taskPriorityLabel = QtWidgets.QLabel(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskPriorityLabel.sizePolicy().hasHeightForWidth())
        self.taskPriorityLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.taskPriorityLabel.setFont(font)
        self.taskPriorityLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.taskPriorityLabel.setObjectName("taskPriorityLabel")
        self.taskPriorityLayout.addWidget(self.taskPriorityLabel)
        self.choosePriority = QtWidgets.QComboBox(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choosePriority.sizePolicy().hasHeightForWidth())
        self.choosePriority.setSizePolicy(sizePolicy)
        self.choosePriority.setMinimumSize(QtCore.QSize(0, 40))
        self.choosePriority.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.choosePriority.setFont(font)
        self.choosePriority.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.choosePriority.setObjectName("choosePriority")
        self.choosePriority.addItem("")
        self.choosePriority.addItem("")
        self.choosePriority.addItem("")
        self.choosePriority.addItem("")
        self.choosePriority.addItem("")
        self.taskPriorityLayout.addWidget(self.choosePriority)
        self.rightMenuButtons.addLayout(self.taskPriorityLayout, 3, 0, 1, 2)
        self.gridLayout_6.addLayout(self.rightMenuButtons, 6, 1, 1, 1)
        self.closeRightMenuButton = QtWidgets.QPushButton(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeRightMenuButton.sizePolicy().hasHeightForWidth())
        self.closeRightMenuButton.setSizePolicy(sizePolicy)
        self.closeRightMenuButton.setMinimumSize(QtCore.QSize(40, 40))
        self.closeRightMenuButton.setMaximumSize(QtCore.QSize(50, 50))
        self.closeRightMenuButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeRightMenuButton.setStyleSheet("color: white;")
        self.closeRightMenuButton.setObjectName("closeRightMenuButton")
        self.gridLayout_6.addWidget(self.closeRightMenuButton, 6, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_6.addLayout(self.verticalLayout, 7, 1, 1, 1)
        self.rightSpacer = QtWidgets.QWidget(self.RightBar)
        self.rightSpacer.setMinimumSize(QtCore.QSize(20, 0))
        self.rightSpacer.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rightSpacer.setObjectName("rightSpacer")
        self.gridLayout_6.addWidget(self.rightSpacer, 4, 2, 1, 1)
        self.saveTaskButton = QtWidgets.QPushButton(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveTaskButton.sizePolicy().hasHeightForWidth())
        self.saveTaskButton.setSizePolicy(sizePolicy)
        self.saveTaskButton.setMaximumSize(QtCore.QSize(16777215, 70))
        self.saveTaskButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveTaskButton.setFont(font)
        self.saveTaskButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveTaskButton.setStyleSheet("color:black;\n"
"background-color: white;\n"
"")
        self.saveTaskButton.setObjectName("saveTaskButton")
        self.gridLayout_6.addWidget(self.saveTaskButton, 9, 1, 1, 1)
        self.horizontalLayout.addWidget(self.RightBar)
        MainWindow.setCentralWidget(self.MainLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.myTaskButton.setText(_translate("MainWindow", "My tasks"))
        self.guideButton.setText(_translate("MainWindow", "Guide"))
        self.logOutButton.setText(_translate("MainWindow", "Log out"))
        self.hideLeftMenu.setText(_translate("MainWindow", "| | |"))
        self.taskListLabel.setText(_translate("MainWindow", "Task List"))
        self.do_label.setText(_translate("MainWindow", "Urgent - Important"))
        self.addDoTask.setText(_translate("MainWindow", "+"))
        self.colorsDoTasks.setText(_translate("MainWindow", "..."))
        self.colorsScheduleTasks.setText(_translate("MainWindow", "..."))
        self.schedule_label.setText(_translate("MainWindow", "Not Urgent - Important"))
        self.addScheduleTask.setText(_translate("MainWindow", "+"))
        self.colorsDeleteTasks.setText(_translate("MainWindow", "..."))
        self.delete_label.setText(_translate("MainWindow", "Not Urgent - Not Important"))
        self.addDeleteTask.setText(_translate("MainWindow", "+"))
        self.colorsDelegateTasks.setText(_translate("MainWindow", "..."))
        self.delegate_label.setText(_translate("MainWindow", "Urgent - Not Important"))
        self.addDelegateTask.setText(_translate("MainWindow", "+"))
        self.deleteTaskButton.setText(_translate("MainWindow", "Delete"))
        self.taskManagerTitle.setText(_translate("MainWindow", "Task Manager"))
        self.taskDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.taskDescription.setPlaceholderText(_translate("MainWindow", "Description"))
        self.taskNameInput.setPlaceholderText(_translate("MainWindow", "Task Name"))
        self.completeLabel.setText(_translate("MainWindow", "Complete"))
        self.taskPriorityLabel.setText(_translate("MainWindow", "Task Priority:"))
        self.choosePriority.setItemText(0, _translate("MainWindow", "None"))
        self.choosePriority.setItemText(1, _translate("MainWindow", "Urgent - Important"))
        self.choosePriority.setItemText(2, _translate("MainWindow", "Urgent - Not Important"))
        self.choosePriority.setItemText(3, _translate("MainWindow", "Not Urgent - Important"))
        self.choosePriority.setItemText(4, _translate("MainWindow", "Not Urgent - Not Important"))
        self.closeRightMenuButton.setText(_translate("MainWindow", "| | |"))
        self.saveTaskButton.setText(_translate("MainWindow", "Save"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())